import { formatCurrency } from '@/lib/site';
import { buildInvoiceSummary } from '@/lib/invoice';

export function buildReceiptPreview(input: {
  companyName: string;
  customerName?: string | null;
  customerEmail?: string | null;
  softwareName: string;
  invoiceNumber?: string | null;
  amount: number;
  currency: string;
  paidAt?: Date | null;
  licenseKey?: string | null;
}) {
  const paidAt = input.paidAt ? input.paidAt.toLocaleString() : 'Pending confirmation';
  return [
    `Receipt from ${input.companyName}`,
    '',
    `Customer: ${input.customerName || 'Customer'}`,
    `Email: ${input.customerEmail || 'Not available'}`,
    `Product: ${input.softwareName}`,
    `Invoice: ${input.invoiceNumber || 'Will be generated after payment confirmation'}`,
    `Paid amount: ${formatCurrency(input.amount, input.currency)}`,
    `Paid at: ${paidAt}`,
    `License key: ${input.licenseKey || 'Will be assigned after payment confirmation'}`,
    '',
    'This is a receipt preview generated by the application starter. Connect an email provider to deliver it automatically.'
  ].join('\n');
}

export function buildReceiptEmail(input: {
  companyName: string;
  customerName?: string | null;
  customerEmail?: string | null;
  softwareName: string;
  invoiceNumber: string;
  amount: number;
  currency: string;
  paidAt: Date;
  licenseKey?: string | null;
}) {
  const subject = `${input.companyName} receipt for ${input.softwareName}`;
  const text = buildReceiptPreview(input);
  const html = `
    <div style="font-family:Arial,sans-serif;line-height:1.6;color:#0f172a;max-width:700px;margin:0 auto;padding:24px;">
      <h1 style="margin-bottom:8px;">Payment receipt</h1>
      <p>Thank you for your purchase from <strong>${input.companyName}</strong>.</p>
      <table style="border-collapse:collapse;width:100%;margin:20px 0;">
        <tr><td style="padding:8px;border:1px solid #cbd5e1;">Customer</td><td style="padding:8px;border:1px solid #cbd5e1;">${input.customerName || 'Customer'}</td></tr>
        <tr><td style="padding:8px;border:1px solid #cbd5e1;">Email</td><td style="padding:8px;border:1px solid #cbd5e1;">${input.customerEmail || 'Not available'}</td></tr>
        <tr><td style="padding:8px;border:1px solid #cbd5e1;">Product</td><td style="padding:8px;border:1px solid #cbd5e1;">${input.softwareName}</td></tr>
        <tr><td style="padding:8px;border:1px solid #cbd5e1;">Invoice</td><td style="padding:8px;border:1px solid #cbd5e1;">${input.invoiceNumber}</td></tr>
        <tr><td style="padding:8px;border:1px solid #cbd5e1;">Paid amount</td><td style="padding:8px;border:1px solid #cbd5e1;">${formatCurrency(input.amount, input.currency)}</td></tr>
        <tr><td style="padding:8px;border:1px solid #cbd5e1;">Paid at</td><td style="padding:8px;border:1px solid #cbd5e1;">${input.paidAt.toLocaleString()}</td></tr>
        <tr><td style="padding:8px;border:1px solid #cbd5e1;">License key</td><td style="padding:8px;border:1px solid #cbd5e1;">${input.licenseKey || 'Assigned after payment confirmation'}</td></tr>
      </table>
      <p>You can sign in to your dashboard anytime to access the product and future updates.</p>
    </div>
  `;
  return { subject, text, html };
}

export function buildInvoiceEmailPreview(input: Parameters<typeof buildInvoiceSummary>[0]) {
  return buildInvoiceSummary(input);
}
